# Generated by Django 3.2.6 on 2021-09-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staffdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centername', models.CharField(max_length=200)),
                ('applicantname', models.CharField(max_length=100)),
                ('applicantmobileno', models.IntegerField()),
                ('applicationtype', models.CharField(max_length=100)),
                ('orderpvccard', models.BooleanField()),
                ('totalcharges', models.CharField(max_length=100)),
            ],
        ),
    ]
